announce = false
description = 'alt:V terratex local development'
gamemode = 'Freeroam'
host = '0.0.0.0'
language = 'en'
modules = [ 'js-module', 'js-bytecode-module', 'csharp-module' ]
name = 'alt:V Server'
players = 256
port = 7788
resources = [ 'terratex-rp']
website = 'example.com'
debug = true
voice = {}

[TerraTex.Database]
host = "localhost"
user = "root"
password = "Asdf123!"
database-name = "TerraTex_RolePlay"