// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TerraTex_RolePlay_AltV_Server.Database;

#nullable disable

namespace TerraTexRolePlayAltVServer.Migrations
{
    [DbContext(typeof(TerraTexDatabaseContext))]
    [Migration("20240918094511_CorrectUserNameField")]
    partial class CorrectUserNameField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TerraTex_RolePlay_AltV_Server.Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("AdminLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DevLevel")
                        .HasColumnType("int");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("DiscordMFAEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DiscordUsername")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong?>("LastHardwareIdExHash")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("LastHardwareIdHash")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("LastIp")
                        .HasColumnType("longtext");

                    b.Property<ulong?>("LastSocialClubId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
