name: tt ci

on:
  push:
    branches: [ master ]

jobs:
  setup:
    name: Checkout
    runs-on: game2
    steps:
      - uses: actions/checkout@v3.5.2
      - name: run build
        run: |        
            dotnet build -c Release
      
