name: tt ci

on:
  push:
    branches: [ master ]

jobs:
  setup:
    name: Checkout
    runs-on: self-game
    steps:
      - uses: actions/checkout@v3.5.2
      - name: run build
        run: |        
            echo ${{ secrets.FILE_CONTENT }} > prod_config
            dotnet build -c Release
      
